[tool.black]
line-length = 79
target-version = ['py36']
skip-string-normalization = true

[tool.isort]
profile = "black"
src_paths = ["src/pydocstyle"]
line_length = 79

[tool.mypy]
ignore_missing_imports = true
strict_optional = true
disallow_incomplete_defs = true
strict = true
follow_imports = 'skip'
